# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# Example configuration for a Shopify App CLI app

client_id = ""
application_url = ""
embedded = true
name = ""
handle = ""

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "products/create",
  "products/update",
  "products/delete"
]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  
]

[pos]
embedded = false
